version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cybercheck-postgres
    environment:
      POSTGRES_DB: cybercheck_db
      POSTGRES_USER: cybercheck_user
      POSTGRES_PASSWORD: cybercheck_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cybercheck_user -d cybercheck_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Server
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cybercheck-backend
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://cybercheck_user:cybercheck_password@postgres:5432/cybercheck_db
      PORT: 3001
      CLIENT_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Frontend Next.js App (Development Mode)
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: cybercheck-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
